// The security suite's report: pure functions shared by `npm run security-suite` (security/run.mjs), the website's
// build (site/build.mjs) and their tests. Node built-ins only; no TypeScript, so the site build can import it as is.

/** The version a run is filed under: the CHANGELOG's newest release, or the next patch when an Unreleased section leads. */
export function releaseVersion(changelog) {
  const heads = [...changelog.matchAll(/^## (.+)$/gm)].map((m) => m[1].split(/\s+—\s+/).map((s) => s.trim()));
  const released = heads.find((h) => /^\d+\.\d+\.\d+$/.test(h[0]) && !h.some((x) => /^unreleased$/i.test(x)));
  const first = heads[0];
  if (!first) return "0.0.0";
  const unreleased = first.some((x) => /^unreleased$/i.test(x));
  if (!unreleased) return first[0];
  if (/^\d+\.\d+\.\d+$/.test(first[0])) return first[0]; // "## 0.2.0 — Unreleased"
  if (!released) return "0.0.1";
  const [a, b, c] = released[0].split(".").map(Number);
  return `${a}.${b}.${c + 1}`;
}

/** Semver-ish sort key for results files (0.1.10 after 0.1.9). */
export const versionKey = (v) => v.split(/[.-]/).map((x) => (/^\d+$/.test(x) ? x.padStart(6, "0") : x)).join(".");

/** The approval eval's per-case lines ("E05 block (expected block) stage=floor · …") → one entry per case. */
export function parseEvalOutput(text) {
  const cases = [];
  for (const line of text.split("\n")) {
    const m = /^(\S+) (allow|block)\s*\(expected (allow|block)\)(.*)$/.exec(line.trim());
    if (m) cases.push({ id: m[1], decision: m[2], expected: m[3], error: /\bERROR\b/.test(m[4]), pass: m[2] === m[3] && !/\bERROR\b/.test(m[4]) });
  }
  return cases;
}

/** Totals over the scenario results (controls are counted apart). */
export function summarize(results) {
  const attacks = results.filter((r) => r.category !== "control");
  const controls = results.filter((r) => r.category === "control");
  const byCategory = [];
  for (const r of attacks) {
    let c = byCategory.find((x) => x.category === r.category);
    if (!c) byCategory.push((c = { category: r.category, name: r.categoryName, total: 0, passed: 0 }));
    c.total++;
    if (r.pass) c.passed++;
  }
  return {
    total: attacks.length, passed: attacks.filter((r) => r.pass).length, failed: attacks.filter((r) => !r.pass).map((r) => r.id),
    controls: { total: controls.length, passed: controls.filter((r) => r.pass).length }, byCategory,
  };
}

const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ");

/** The per-release Markdown report (security/results/<version>.md). */
export function renderMarkdown(report) {
  const s = report.summary;
  const out = [];
  out.push(`# Security suite results: ${report.version}`);
  out.push("");
  out.push(`Generated by \`npm run security-suite\` on ${report.date}${report.commit ? ` at commit \`${report.commit}\`` : ""}. How to run it and what it covers: [security/README.md](../README.md).`);
  out.push("");
  out.push(`**${s.passed} of ${s.total} attacks stopped.** ${s.failed.length ? `Not stopped: ${s.failed.join(", ")}.` : "None went through."} Controls (ordinary work still runs on the same test bench): ${s.controls.passed} of ${s.controls.total}.`);
  out.push("");
  out.push("No model, no API key and no network. The AI reviewer is replaced by one that approves everything, so every stop below comes from Synapse's fixed code.");
  out.push("");
  out.push("| Category | Stopped |");
  out.push("| --- | --- |");
  for (const c of s.byCategory) out.push(`| ${cell(c.name)} | ${c.passed} of ${c.total} |`);
  out.push("");
  let cat = null;
  for (const r of report.scenarios) {
    if (r.category !== cat) {
      cat = r.category;
      out.push(`## ${r.categoryName}`);
      out.push("");
      out.push("| Id | Attack | Expected | Result | Stopped by |");
      out.push("| --- | --- | --- | --- | --- |");
    }
    out.push(`| ${r.id} | ${cell(r.attack)} | ${cell(r.expected)} | ${r.pass ? "Pass" : "**FAIL**"}: ${cell(r.actual)} | ${cell(r.layer)} |`);
    if (report.scenarios[report.scenarios.indexOf(r) + 1]?.category !== cat) out.push("");
  }
  out.push("## Model tier (optional)");
  out.push("");
  const m = report.model;
  if (!m || m.status === "skipped") {
    out.push(`Skipped. ${m?.reason ?? "Run with `--with-model` to include it."}`);
  } else {
    const blocked = m.cases.filter((c) => c.decision === "block").length;
    out.push(`${m.status === "passed" ? "Passed" : "**Failed**"}: the approval eval's must-block cases through the real AI reviewer (${m.via}). ${blocked} of ${m.cases.length} blocked${m.cases.some((c) => c.error) ? `, ${m.cases.filter((c) => c.error).length} errors` : ""}.`);
    out.push("");
    out.push("| Case | Decision |");
    out.push("| --- | --- |");
    for (const c of m.cases) out.push(`| ${c.id} | ${c.pass ? "blocked" : `**${c.error ? "error" : c.decision}**`} |`);
  }
  out.push("");
  out.push(`Environment: Node ${report.node}, ${report.platform}.`);
  return `${out.join("\n")}\n`;
}
