import { STR } from "@synapse/shared";

export type ParityEntry = { tool: string } | { userOnly: string } | { laterPhase: 2 | 3 | 5; tool: string };

export const USER_ONLY_TEXT = (row: string): string => STR.userOnly(row);

/** §4.5 commands (plus Phase 4 additions) that change product state. */
export const SPEC_GATEWAY_COMMANDS: readonly string[] = [
  // Transcript
  "sendPrompt", "respondToWidget", "dismissWidget", "submitSecret", "resolveAutoReviewApproval", "resolveLocalToolPermission", "reactToMessage", "interruptAgent",
  // Agents and groups
  "createAgent", "kickstartAgent", "updateAgent", "deleteAgent", "duplicateAgent", "createGroup", "setGroupMembers", "setAgentUnread",
  "setAgentNotificationsEnabled", "setAgentHiddenFromSidebar", "setAgentPinned", "openAgent", "setWindowFocused", "setAgentAvatarBytes",
  "generateAgentAvatar", "broadcastToAgents", "deleteAgentMemory", "clearAgentMemories", "addAgentMemory", "updateAgentMemory",
  // Sessions and context
  "compactAgentNow", "newAgentSession", "setAgentHistoryKeep",
  // Routines and skills
  "setAgentAutomationEnabled", "createAgentAutomation", "updateAgentAutomation", "deleteAgentAutomation", "runAgentAutomationNow",
  "rotateAutomationWebhookKey", "setListenerCredentials", "addMailbox", "createWorkflow", "updateWorkflow", "setAgentWorkflowEnabled",
  "deleteWorkflow", "runAgentWorkflowNow", "importWorkflowText", "importWorkflowUrl", "importWorkflowFolder",
  "setStandupSettings", "runStandupNow",
  // Box and computer
  "ensureForeverBox", "updateForeverBox", "recoverForeverBox", "resetForeverBox", "snapshotBoxStoreNow", "handBackForeverBox",
  "startTeachRecording", "stopTeachRecording", "pauseTeachRecording", "resumeTeachRecording", "discardTeachRecording",
  // Phase 3 box and computer additions
  "ensureDisplay", "setTakeoverActive", "openComputerApp", "submitForm", "openDiskSaver", "restoreSnapshot", "deleteSnapshot", "prepareBoxRestart", "setBoxMaintenance",
  // Trays, attachments, settings, secrets
  "dismissTray", "clearTrays", "uploadAttachment", "setHostSettings", "setMacTimeZone", "setNetworkPause", "setBotSecrets",
  // MCP and plugins
  "installPlugin", "uninstallPlugin", "setMcpToolEnabled", "startMcpAuth", "completeMcpOAuth",
  // Templates
  "exportTemplate", "importTemplate", "deleteTemplate", "sharePayload",
  // Phase 5 additions (usage, MCP, marketplaces, templates, local execution, avatars, voice, onboarding, memory, keys, follow-ups)
  "setBudget", "approveBudget", "clearTaskAlert", "dismissBudgetPrompt", "setMonthlyBudget", "setSpendMeter", "recordMacUsage", "addMcpServer", "removeMcpServer", "renameMcpAccount", "setMcpInstructions", "restartMcpServers", "setMcpServerEnabled", "setMcpServerTrusted", "setMcpServerHeader", "setOAuthLoopbackPort",
  "addPluginMarketplace", "removePluginMarketplace", "draftTemplate", "setLocalComputer", "setLocalBrowserAllowed", "setLocalMacAppAllowed", "undoMacAction", "setLocalDryRun", "resetLocalPolicy", "restoreLocalBotModes", "dismissLocalPolicyReset", "registerLocalComputer",
  "localExecHeartbeat", "localExecOutput", "localExecDone", "localExecUpload", "clearAgentAvatar", "setAgentVoice", "noteVoiceCall", "startCall", "addToCall", "removeFromCall", "endCall", "getCallGreetings", "wrapUpCall", "voiceSpeculate", "voiceSpeculateCancel", "voiceLatencyNotice",
  "completeOnboarding", "setMemoryMode", "setAgentFollowups", "setAgentEngineeringMode", "setAgentPermMode", "setAgentNoLimits", "setAgentSaveUsage", "setAgentComputerPerception",
  // Settings → Account (the API key)
  "setApiKey", "clearApiKey", "testAuthConnection", "checkApiKey",
  // Settings → Account (model provider keys and consent)
  "setProviderKey", "clearProviderKey", "testProviderKey", "consentProvider", "runSafetyCheck", "cancelSafetyCheck", "setSafetyReviewer", "runProviderConformance",
  // Settings → Account, coding CLIs over ACP (Wave 3)
  "consentAcpVendor", "startAcpLogin", "checkAcpLogin", "installAcpVendor", "removeAcpVendor",
  "answerBotCall", "setBotCallPermission",
  // Built-in Google connector (ORIG-GOOGLE)
  "setGoogleClient", "startGoogleAuth", "disconnectGoogle", "setAgentGoogle", "setAgentGoogleAccount", "setAgentEmailIn",
  // Apps through Composio
  "setComposioKey", "clearComposioKey", "acceptComposioDisclosure", "connectComposioApp", "disconnectComposioApp", "setComposioGrant", "renameComposioAccount", "setMcpServerBots",
  // google-setup: the guided task and the weekly sign-in check
  "startGoogleSetupTask", "cancelGoogleSetupTask", "setGoogleReconnectCheck",
  // Per-Bot GitHub sign-in (bug-log 195)
  "startGitHubSignIn", "signOutGitHub",
  // 0.1.4 first-run: the coding-agent card's Stop
  "cancelCodingAgent",
  // 0.1.4: Synapse's MCP server (host/mcp-server)
  "mcpStartTask",
  // 4.4: the app's own connector (Telegram) reporting its health
  "reportConnectorHealth",
];

/** §4.5 commands (plus Phase 4 additions) that only read. */
export const READ_ONLY_COMMANDS: readonly string[] = [
  "getAgentTranscriptPage", "getAgentTranscriptTail", "getAgentThread", "promptAcceptanceStatus", "getConversationOutline",
  "listAgents", "countAgents", "searchAgents", "search", "getAgentAvatar", "getSubagents", "getAsyncTasks", "getAgentMemories", "getHistoryArchiveStats", "getAgentContext",
  "getAgentAutomations", "listAllAutomations", "getStandup", "getAutomationWebhook", "getWorkflows", "getWorkflow",
  "getForeverBoxStatus", "getBoxStoreStatus", "getTeachRecordingStatus", "getHealth",
  "getTrays", "readAttachmentChunk", "readWorkspaceFile", "getHostSettings", "getBotSecretsStatus",
  "listPlugins", "searchCatalog", "listMcpServers", "previewTemplateImport", "previewShareImport", "getUsage", "getUsageDashboard", "getBudgets", "getRuntimeStats",
  "getDisplays", "getDiskPressure", "listSnapshots", "listBotCalls",
  "getMarketplace", "getCatalogEntry", "listPluginMarketplaces", "getTemplate", "listStarterTemplates", "getLocalComputer", "getLocalPolicyStatus", "getLocalPolicyReset", "getLocalBotMode", "getLocalBrowserAllowed", "getLocalMacAppAllowed", "getBrowserUsage",
  "listMacActions", "exportMacActions", "getLocalDryRun",
  "readLocalFile", "getNetworkStats", "getOnboarding", "listCodingAgents", "getPhase5Settings", "getGoogleStatus", "getGoogleReconnectCheck", "getComposioStatus", "getGitHubStatus",
  "getAuth", "getProviders", "getAcpVendors", "getSafetyReviewer", "getModelCatalog", "getCostPreview", "getModelAccess", "getBudgetPrompt", "getSpendMeter", "macClaudeAuth",
  "mcpListBots", "mcpTaskStatus", "mcpTaskResult",
  // 4.4: connector health
  "getConnectorHealth",
];

export const PARITY: Record<string, ParityEntry> = {
  sendPrompt: { userOnly: "the user's own messages" },
  respondToWidget: { userOnly: "answering widgets" },
  dismissWidget: { userOnly: "answering widgets" },
  submitSecret: { userOnly: "secret values" },
  resolveAutoReviewApproval: { userOnly: "answering approval cards" },
  resolveLocalToolPermission: { userOnly: "answering approval cards" },
  setMcpServerEnabled: { userOnly: "turning a connector on or off" },
  setMcpServerTrusted: { userOnly: "trusting a connector (P5 review I6)" },
  setMcpServerHeader: { userOnly: "secret values" },
  setOAuthLoopbackPort: { userOnly: "the Mac's OAuth loopback channel" },
  reactToMessage: { userOnly: "the user's own reactions" },
  setStandupSettings: { userOnly: "the daily standup's settings" },
  runStandupNow: { userOnly: "running the daily standup" },
  interruptAgent: { userOnly: "the user's Stop button" },
  cancelCodingAgent: { userOnly: "the user's Stop button (a Bot cancels its own with CodingAgent)" },
  createAgent: { tool: "CreateAgent" },
  kickstartAgent: { tool: "CreateAgent" },
  updateAgent: { tool: "UpdateAgent" },
  deleteAgent: { tool: "DeleteAgent" },
  duplicateAgent: { tool: "DuplicateAgent" },
  createGroup: { tool: "CreateChannel" },
  setGroupMembers: { tool: "UpdateChannel" },
  setAgentUnread: { userOnly: "view state" },
  setAgentNotificationsEnabled: { tool: "UpdateAgent" },
  setAgentHiddenFromSidebar: { tool: "UpdateAgent" },
  setAgentPinned: { tool: "UpdateAgent" },
  openAgent: { userOnly: "view state" },
  setWindowFocused: { userOnly: "view state" },
  setAgentAvatarBytes: { laterPhase: 5, tool: "update_state:avatar" },
  generateAgentAvatar: { laterPhase: 5, tool: "update_state:avatar" },
  broadcastToAgents: { userOnly: "the user's own broadcast" },
  deleteAgentMemory: { laterPhase: 2, tool: "update_state:memory" },
  clearAgentMemories: { laterPhase: 2, tool: "update_state:memory" },
  addAgentMemory: { laterPhase: 2, tool: "update_state:memory" },
  updateAgentMemory: { laterPhase: 2, tool: "update_state:memory" },
  compactAgentNow: { userOnly: "context compaction" },
  setAgentHistoryKeep: { userOnly: "how much history a Bot keeps (a cost setting)" },
  newAgentSession: { userOnly: "starting a new session" },
  setAgentAutomationEnabled: { tool: "update_state:routine" },
  createAgentAutomation: { tool: "update_state:routine" },
  updateAgentAutomation: { tool: "update_state:routine" },
  deleteAgentAutomation: { tool: "update_state:routine" },
  runAgentAutomationNow: { tool: "update_state:routine" },
  rotateAutomationWebhookKey: { userOnly: "webhook keys (shown only to the user)" },
  setListenerCredentials: { userOnly: "secret values" },
  addMailbox: { userOnly: "secret values" },
  createWorkflow: { laterPhase: 2, tool: "update_state:workflow" },
  updateWorkflow: { laterPhase: 2, tool: "update_state:workflow" },
  setAgentWorkflowEnabled: { laterPhase: 2, tool: "update_state:workflow" },
  deleteWorkflow: { laterPhase: 2, tool: "update_state:workflow" },
  runAgentWorkflowNow: { laterPhase: 2, tool: "Skill" },
  importWorkflowText: { laterPhase: 2, tool: "update_state:workflow" },
  importWorkflowUrl: { laterPhase: 2, tool: "update_state:workflow" },
  importWorkflowFolder: { laterPhase: 2, tool: "update_state:workflow" },
  ensureForeverBox: { laterPhase: 3, tool: "ComputerControl" },
  updateForeverBox: { laterPhase: 3, tool: "ComputerControl" },
  recoverForeverBox: { laterPhase: 3, tool: "ComputerControl" },
  resetForeverBox: { laterPhase: 3, tool: "ComputerControl" },
  snapshotBoxStoreNow: { laterPhase: 3, tool: "ComputerControl" },
  handBackForeverBox: { userOnly: "box handoffs" },
  ensureDisplay: { userOnly: "view state" },
  setTakeoverActive: { userOnly: "box handoffs" },
  openComputerApp: { userOnly: "opening apps on the shared computer" },
  submitForm: { userOnly: "answering widgets" },
  openDiskSaver: { laterPhase: 3, tool: "ComputerControl" },
  restoreSnapshot: { laterPhase: 3, tool: "ComputerControl" },
  deleteSnapshot: { laterPhase: 3, tool: "ComputerControl" },
  prepareBoxRestart: { laterPhase: 3, tool: "ComputerControl" },
  setBoxMaintenance: { userOnly: "the app's own box updates" },
  startTeachRecording: { userOnly: "the user's demonstration" },
  stopTeachRecording: { userOnly: "the user's demonstration" },
  pauseTeachRecording: { userOnly: "the user's demonstration" },
  resumeTeachRecording: { userOnly: "the user's demonstration" },
  discardTeachRecording: { userOnly: "the user's demonstration" },
  dismissTray: { userOnly: "view state" },
  clearTrays: { userOnly: "view state" },
  uploadAttachment: { userOnly: "the user's own attachments" },
  setHostSettings: { tool: "update_state:account_settings" },
  setMacTimeZone: { userOnly: "the Mac's own clock" },
  setNetworkPause: { userOnly: "the app's check of the Bots' computer's network guard" },
  setBotSecrets: { userOnly: "secret values" },
  installPlugin: { laterPhase: 5, tool: "InstallPlugin" },
  uninstallPlugin: { laterPhase: 5, tool: "UninstallPlugin" },
  setMcpToolEnabled: { laterPhase: 5, tool: "SetMcpToolEnabled" },
  startMcpAuth: { laterPhase: 5, tool: "AuthenticateMcpServer" },
  completeMcpOAuth: { userOnly: "OAuth sign-in in the browser" },
  exportTemplate: { laterPhase: 5, tool: "Template" },
  importTemplate: { laterPhase: 5, tool: "Template" },
  sharePayload: { userOnly: "sharing a Bot" },
  deleteTemplate: { laterPhase: 5, tool: "Template" },
  setBudget: { userOnly: "billing" },
  approveBudget: { userOnly: "answering approval cards" },
  clearTaskAlert: { userOnly: "billing" },
  dismissBudgetPrompt: { userOnly: "billing" },
  setMonthlyBudget: { userOnly: "billing" },
  setSpendMeter: { userOnly: "billing" },
  recordMacUsage: { userOnly: "billing" },
  addMcpServer: { laterPhase: 5, tool: "AddMcpServer" },
  removeMcpServer: { laterPhase: 5, tool: "UninstallMcpServer" },
  renameMcpAccount: { laterPhase: 5, tool: "RenameMcpAccount" },
  setMcpInstructions: { laterPhase: 5, tool: "SetMcpInstructions" },
  restartMcpServers: { laterPhase: 5, tool: "RestartMcpServers" },
  addPluginMarketplace: { userOnly: "plugin sources" },
  removePluginMarketplace: { userOnly: "plugin sources" },
  draftTemplate: { laterPhase: 5, tool: "Template" },
  setLocalComputer: { userOnly: "local execution policy" },
  setLocalBrowserAllowed: { userOnly: "the browser permission on the Mac" },
  setLocalMacAppAllowed: { userOnly: "the app permission on the Mac" },
  undoMacAction: { userOnly: "undoing a Bot's change on the Mac" },
  setLocalDryRun: { userOnly: "dry run on the Mac" },
  resetLocalPolicy: { userOnly: "resetting the permission records on the Mac" },
  restoreLocalBotModes: { userOnly: "turning a Bot's mode back on on the Mac" },
  dismissLocalPolicyReset: { userOnly: "the permission-reset prompt on the Mac" },
  registerLocalComputer: { userOnly: "local execution policy" },
  localExecHeartbeat: { userOnly: "the Mac's local-execution channel" },
  localExecOutput: { userOnly: "the Mac's local-execution channel" },
  localExecDone: { userOnly: "the Mac's local-execution channel" },
  localExecUpload: { userOnly: "the Mac's local-execution channel" },
  clearAgentAvatar: { laterPhase: 5, tool: "update_state:avatar" },
  setAgentVoice: { tool: "UpdateAgent" },
  noteVoiceCall: { userOnly: "voice call markers" },
  startCall: { userOnly: "voice calls" },
  addToCall: { userOnly: "voice calls" },
  removeFromCall: { userOnly: "voice calls" },
  endCall: { userOnly: "voice calls" },
  getCallGreetings: { userOnly: "voice calls" },
  wrapUpCall: { userOnly: "voice calls" },
  voiceSpeculate: { userOnly: "voice calls" },
  voiceSpeculateCancel: { userOnly: "voice calls" },
  voiceLatencyNotice: { userOnly: "voice calls" },
  completeOnboarding: { userOnly: "onboarding" },
  setApiKey: { userOnly: "secret values" },
  clearApiKey: { userOnly: "secret values" },
  testAuthConnection: { userOnly: "account sign-in" },
  checkApiKey: { userOnly: "account sign-in (spends one tiny message)" },
  setProviderKey: { userOnly: "secret values" },
  clearProviderKey: { userOnly: "secret values" },
  testProviderKey: { userOnly: "account sign-in (spends one tiny message)" },
  consentProvider: { userOnly: "data-sharing consent is the user's own" },
  consentAcpVendor: { userOnly: "data-sharing consent is the user's own" },
  startAcpLogin: { userOnly: "account sign-in" },
  checkAcpLogin: { userOnly: "account sign-in" },
  installAcpVendor: { userOnly: "installing software on the Bots' computer as root" },
  removeAcpVendor: { userOnly: "installing software on the Bots' computer as root" },
  runSafetyCheck: { userOnly: "safety settings (spends model calls)" },
  setSafetyReviewer: { userOnly: "safety settings" },
  cancelSafetyCheck: { userOnly: "safety settings" },
  runProviderConformance: { userOnly: "model checks (spends model calls)" },
  answerBotCall: { userOnly: "answering a Bot's call" },
  setBotCallPermission: { userOnly: "which Bots may call the user" },
  setMemoryMode: { userOnly: "memory settings" },
  setAgentFollowups: { userOnly: "follow-up settings" },
  setAgentEngineeringMode: { userOnly: "engineering mode" },
  setAgentPermMode: { userOnly: "permission mode" },
  setAgentNoLimits: { userOnly: "permission mode" },
  setAgentSaveUsage: { userOnly: "usage settings" },
  setAgentComputerPerception: { userOnly: "computer perception mode" },
  setGoogleClient: { userOnly: "secret values" },
  startGoogleAuth: { userOnly: "OAuth sign-in in the browser" },
  disconnectGoogle: { userOnly: "connected accounts" },
  setAgentGoogle: { userOnly: "connected accounts" },
  setAgentGoogleAccount: { userOnly: "connected accounts" },
  setAgentEmailIn: { userOnly: "connected accounts" },
  setComposioKey: { userOnly: "secret values" },
  clearComposioKey: { userOnly: "secret values" },
  acceptComposioDisclosure: { userOnly: "connected accounts" },
  connectComposioApp: { userOnly: "OAuth sign-in in the browser" },
  disconnectComposioApp: { userOnly: "connected accounts" },
  setComposioGrant: { userOnly: "connected accounts" },
  renameComposioAccount: { userOnly: "connected accounts" },
  setMcpServerBots: { userOnly: "connected accounts" },
  startGoogleSetupTask: { userOnly: "connected accounts" },
  cancelGoogleSetupTask: { userOnly: "connected accounts" },
  setGoogleReconnectCheck: { userOnly: "connected accounts" },
  startGitHubSignIn: { userOnly: "GitHub sign-in in the browser" },
  signOutGitHub: { userOnly: "connected accounts" },
  mcpStartTask: { userOnly: "an outside app's request over Synapse's MCP server" },
  reportConnectorHealth: { userOnly: "the app's own Telegram connection reporting its state" },
};
