/** Bug 198: the phone app's words. Titles and labels only. */
export const PS = {
  app: "Synapse",
  pairTitle: "Pair this phone",
  codeLabel: "Pairing code",
  pair: "Pair",
  badCode: "That code didn't work",
  bots: "Bots",
  noBots: "No Bots yet",
  call: (name: string) => `Call ${name}`,
  alerts: "Call alerts",
  alertsOn: "On",
  turnOn: "Turn on",
  alertsBlocked: "Blocked in Settings",
  iosHint: "Add to Home Screen for call alerts",
  connecting: "Connecting",
  listening: "Listening",
  speaking: "Speaking",
  muted: "Muted",
  ended: "Call ended",
  failed: "Couldn't connect",
  elsewhere: "Answered elsewhere",
  mute: "Mute",
  unmute: "Unmute",
  hangUp: "Hang up",
  you: "You",
  offline: "Synapse isn't reachable",
  retry: "Retry",
  micDenied: "Microphone access is off",
  isCalling: (name: string) => `${name} is calling`,
  answer: "Answer",
  decline: "Decline",
  unpair: "Unpair",
} as const;
