/** Bytes as Finder shows them: decimal GB, one decimal place. */
const gbText = (bytes: number): string => `${(Math.round(bytes / 1e8) / 10).toFixed(1)} GB`;

/** Settings → Backups, Settings → Diagnostics and the crash toast. */
export const STRO = {
  backups: "Backups",
  backupTitle: "Back up",
  backupHelp: "One encrypted file holds your Bots, their memories, chats, schedules and usage, and this Mac's Synapse settings. Secrets stay encrypted.",
  backupNow: "Back up now",
  backingUp: "Backing up…",
  lastBackup: (when: string) => `Last backup: ${when}`,
  neverBackedUp: "No backup yet",
  autoBackup: "Back up automatically every day",
  keepLast: "Keep",
  keepN: (n: number) => `Last ${n}`,
  folder: "Folder",
  changeFolder: "Change…",
  useDefaultFolder: "Use default",
  recoveryTitle: "Your recovery code",
  recoveryHelp: "Backups are encrypted with a key in this Mac's keychain. To restore on another Mac you need this code. It is shown once.",
  copy: "Copy",
  saveToFile: "Save to file…",
  savedIt: "I saved it",
  archives: "Backups in this folder",
  noArchives: "No backups in this folder yet.",
  safetyBackup: "Safety backup",
  reveal: "Show in Finder",
  restore: "Restore…",
  restoreFromFile: "Restore from file…",
  previewTitle: "Restore this backup?",
  previewMeta: (date: string, size: string, n: number) => `${date} · ${size} · ${n === 1 ? "1 Bot" : `${n} Bots`}`,
  restoreWarning: "This replaces your Bots, chats, memories and settings with the ones in this backup. A safety backup of what is here now is made first. Bots stop while the host restarts.",
  enterRecoveryCode: "Recovery code",
  open: "Open",
  restoreConfirm: "Restore",
  restoring: "Restoring… the host restarts, this can take a minute.",
  restored: (n: number, verified: boolean) => `Restored ${n === 1 ? "1 Bot" : `${n} Bots`}.${verified ? " Checked: the host is healthy and every Bot is back." : " The Bot count didn't match the backup; check your Bots."}`,
  macSecretsSkipped: "This backup came from another Mac, so its saved secrets can't be opened here. Enter them again in each Bot's settings.",
  hostSealedSkipped: "MCP, Google and connector sign-ins were sealed on another computer; connect them again.",
  releaseFolder: "Release folder",
  // UI polish pass (brief 2): the second group under System → Updates (the folder and the feed).
  releaseSource: "Release source",
  releaseFolderHelp: "Synapse looks here first for a newer build (npm run release puts one here). A build is installed only if it is signed by Synapse Local Signing; if it doesn't start within a minute, Synapse goes back to this version.",
  diagnostics: "Diagnostics",
  diagnosticsHelp: "Problems Synapse recovered from. Reports stay on this Mac; nothing is ever uploaded.",
  noProblems: "No problems recorded.",
  // bug-log 128: the Mac's free space (a GB here is Finder's: 10^9 bytes)
  gb: gbText,
  macDiskTitle: "Your Mac is almost out of space",
  macDiskLow: (freeBytes: number) => `Your Mac is almost out of space (${gbText(freeBytes)} free). Synapse's backups and Bots may stop working.`,
  dismiss: "Dismiss",
  storage: "Storage",
  storageHelp: "Free space on this Mac and on Synapse's computer, checked every 10 minutes.",
  thisMac: "This Mac",
  synapseComputer: "Synapse's computer",
  gbFree: (bytes: number) => `${gbText(bytes)} free`,
  notKnownYet: "Not known yet",
  copyReport: "Copy report",
  revealReport: "Show in Finder",
  reportCopied: "Report copied",
  recoveredToast: "Synapse recovered from a problem",
  view: "View",
  kind: {
    "main-crash": "App error", "renderer-crash": "Window crashed", "renderer-error": "Window error", "unhandled-rejection": "Unhandled error",
    "helper-exit": "Voice helper stopped", "host-crash": "Host crashed", "host-restart": "Host restarted", "child-crash": "App process crashed",
  } as Record<string, string>,
};
