import type { Presence } from "./bots";

/** The app's name (bug 284: it was Bots). "Bot" and "Bots" still name its assistants. */
export const APP_NAME = "Synapse";

export function possessive(name: string): string {
  return name.endsWith("s") ? `${name}'` : `${name}'s`;
}

/** The box the Bots work on: the Bots' (the assistants'), never the app's, so it keeps its name after the rename. */
export const COMPUTER_NAME = "Bots' computer";

export function formatDuration(ms: number): string {
  const s = Math.max(1, Math.round(ms / 1000));
  if (s < 60) return `${s}s`;
  return `${Math.round(s / 60)}m`;
}

export const STR = {
  connStarting: "Starting your computer",
  connReconnecting: "Reconnecting",
  connUnreachable: "Couldn't reach Bots' computer",
  hostNoAnswer: "The Bots' computer didn't answer. Try again.",
  hostOddPort: (port: number) => `The Bots' computer reported a port Synapse doesn't use (${port}). Retry; if it happens again, Recover.`,
  hostNeedsUpdate: "The Bots' software needs an update before Synapse can connect, and it didn't finish. Retry.",
  hostNotConnected: "Synapse isn't connected to the Bots' computer yet. Try again in a moment.",
  hostTimeout: "The Bots' computer took too long to answer. Try again.",
  hostBadAnswer: (status: number) => `The Bots' computer sent an answer Synapse couldn't read (HTTP ${status}). Try again.`,
  retry: "Retry",
  newBotName: "New Bot",
  maxBots: "50 is the maximum",
  toLabel: "To:",
  toPlaceholder: "Search or create Bots",
  createNewBot: "Create new Bot",
  newChat: "New chat",
  createNamedBot: (name: string) => `Create "${name}" Bot`,
  createGroupChat: "Create group chat",
  messagePlaceholder: (name: string) => `Message ${name}`,
  newChatPlaceholder: "Message Bot",
  working: "Working",
  /** Bug #55: the avatar's hover tooltip, "<what it is doing> · <activity.detail>". Idle has none. */
  avatarAction: { thinking: "Thinking", working: "Working", searching: "Searching", sending: "Sending", loading: "Loading", orbit: "Running a task" } as Record<Exclude<Presence, "idle">, string>,
  search: "Search",
  screenCaption: (name: string) => `${possessive(name)} screen`,
  approvalTitle: {
    box_shell: "Your Bot would like to run a command",
    host_shell: "Your Bot would like to run a command",
    mcp: "Your Bot would like to use a connected service",
    subagent: "Your Bot would like to start a task",
    computer: "Held for Your OK",
    automation_write: "Held for Your OK",
    cloud_agent: "Held for Your OK",
    control_plane: "Held for Your OK",
  } as Record<string, string>,
  runsOnBox: `Runs on ${COMPUTER_NAME}`,
  runsOnLocal: "Runs on your own computer",
  allowOnce: "Allow once",
  planTitle: "Approve plan",
  planSummary: (title: string, steps: number) => `Plan: ${title} · ${steps} ${steps === 1 ? "step" : "steps"}`,
  approve: "Approve",
  alwaysAllow: "Always allow",
  deny: "Deny",
  settledTitle: { approved: "Action approved", always: "Action approved", denied: "Action denied", expired: "Approval expired", stopped: "Stopped by you" } as Record<string, string>,
  settledLabel: { approved: "Allowed once", always: "Always allowed", denied: "Denied", expired: "Expired", stopped: "Stopped by you" } as Record<string, string>,
  /** New-user walk, finding 3: a step the user's Stop cut off before it ran. */
  stoppedStep: (what: string) => `Stopped: ${what}`,
  /** New-user walk, finding 6: a step held on an approval card. */
  waitingStep: (what: string) => `Waiting for your OK: ${what}`,
  statusUnavailable: "Status unavailable",
  /** settings-persist: a switch whose save failed goes back to what is saved and says this, next to it. */
  settingNotSaved: "Couldn't save. Try again.",
  /** settings-persist: a switch whose saved value couldn't be read is not drawn as Off. */
  settingNotLoaded: "Couldn't load this setting.",
  details: "Details",
  viewFullRequest: "View the full request ›",
  viewFullRequestLabel: "View the full request",
  manageAutoReviewIn: "You can manage Auto-review in",
  settings: "Settings",
  ruleAdded: (rule: string) => `Added to your Auto-review rules as always allowed: “${rule}”`,
  ruleLoosened: (rule: string, what: string) => `“${rule}” no longer asks for ${what}`,
  approvalNeeded: (summary: string) => `Approval needed: ${summary}`,
  trayBotFailed: "Bot failed to respond",
  trayBotCrashedDetail: "The Bot crashed 3 times in 10 minutes; retrying in 60 s.",
  trayOverloaded: "The model service is busy",
  trayIntroFailed: "Your Bot couldn't introduce itself",
  traySignIn: "Anthropic API key problem",
  trayUsage: "Usage limit reached",
  trayReviewerDown: "Auto-review can't be reached",
  traySettingsReset: "Your settings couldn't be read",
  traySettingsResetDetail: (kept: string) => `They were reset to the defaults — set your theme, time zone and Auto-review rules again in Settings. The unreadable file was kept at ${kept}.`,
  trayModelUnavailable: "This Bot's model isn't available to your API key",
  notifications: "Notifications",
  clear: "Clear",
  general: "General",
  bot: "Bot",
  autoReview: "Auto-review",
  autoReviewDesc: `${APP_NAME} looks over every step a Bot takes and stops to ask when one needs your OK. Add rules for the steps you always allow.`,
  rulesHelper: 'One short rule per line, in plain words. When rules disagree, "Ask first" wins.',
  rulesWhen: "When a Bot wants to:",
  rulesPlaceholder: "e.g. answer my emails",
  rulesItShould: "It should:",
  allowAutomatically: "Allow automatically",
  askFirst: "Ask first",
  addRule: "Add rule",
  trustedPeople: "Trusted people",
  trustedPlaceholder: "name@example.com",
  add: "Add",
  // Hand-testing round: edit mode must name itself and be escapable.
  saveRule: "Save rule",
  rulesAction: "Action",
  rulesBehavior: "Behavior",
  rulesFooter: "Your rules are private to you. The built-in safety checks apply no matter what.",
  deleteConfirm: (name: string) => `Delete ${name}? Its profile, chat history and routines go with it. Files and sign-ins on the computer are kept.`,
  deleteBot: "Delete Bot",
  // UI polish pass (brief 2): the destructive confirm names its act; the title is the question, one line says what goes.
  deleteTitle: (name: string) => `Delete ${name}?`,
  deleteLine: "Its chat history and routines go with it. Files and sign-ins on the computer are kept.",
  deleteVerb: "Delete",
  cancel: "Cancel",
  setAvatar: "Set avatar",
  reset: "Reset",
  name: "Name",
  description: "Description",
  /** New-user walk, finding 13: a Bot's system prompt, in Bot settings. */
  instructions: "Instructions",
  model: "Model",
  effort: "Effort",
  engine: "Engine",
  stop: "Stop",
  created: "Created",
  renamedTo: "Renamed to",
  activitySummary: (ms: number, steps: number) => `Worked for ${formatDuration(ms)} · ${steps} step${steps === 1 ? "" : "s"}`,
  moreSteps: (n: number) => `+${n} more step${n === 1 ? "" : "s"}`,
  andMore: (n: number) => `and ${n} more`,
  batchTitle: (bot: string, verb: string, n: number, noun: string) => `${bot} wants to ${verb} ${n} ${noun}`,
  fullRequest: "Full request",
  copyRequestId: "Copy request ID",
  close: "Close",
  marketplace: "Marketplace",
  pin: "Pin",
  unpin: "Unpin",
  openAccountMenu: "Open account menu",
  typing: "Typing",
  newMessages: "New messages",
  botCreateHourCap: "Not created: Bots can create at most 5 Bots an hour. Try again later or ask the user to create it.",
  botCreateDayCap: "Not created: Bots can create at most 20 Bots a day. Try again later or ask the user to create it.",
  // routines (RTN-*)
  routines: "Routines",
  routinesEmpty: "Nothing scheduled",
  paused: "Paused",
  active: "Active",
  testRun: "Test run",
  testRunWarning: "Test run does real work.",
  runHistory: "Run history",
  noRunsYet: "No runs yet",
  whenToRun: "When to run",
  instruction: "Instruction",
  deleteRoutine: "Delete routine",
  routineUsageHelp: "Each run is billed to your Anthropic API key.",
  scheduleInvalid: "Enter a valid schedule",
  scheduleSpacing: "Leave 5 minutes or more between a routine's runs",
  scheduleAmbiguous: (text: string, why: string, question: string) => `Enter a valid schedule — "${text}" is ambiguous: ${why}. Ask the user: ${question}`,
  availableAfterSave: "Save the routine to use this",
  postTo: "POST to",
  webhookKey: "Key",
  webhookHeader: "Header",
  rotateKey: "Rotate",
  routineMaxReached: "Not saved — a Bot can have at most 50 routines.",
  runInterrupted: "Interrupted by a host update; resuming after restart.",
  // Bug 44: the old session could not be read, so the handoff recap is only what the host could still see.
  rolloverTailLost: "(The previous session's own file could not be read, so this recap is only what was still visible in the conversation — earlier detail is gone. If the user refers to something you cannot find, say so rather than guessing.)",
  // Bug 44: a routine the host cannot arm says so on its own row instead of sitting there listed as Active.
  routineBadSchedule: (schedule: string) => `I can't read the schedule "${schedule}".`,
  routineBadEmailQuery: (query: string) => `I can't read the email filter "${query}".`,
  routineNoMailbox: (account: string) => `no mailbox called "${account}" is set up for this Bot`,
  routineMailboxUnreachable: (account: string) => `Can't reach the mailbox "${account}" — check its server and app password, then use Add mailbox on this routine to enter them again under the name "${account}". Watching resumes as soon as it connects.`,
  webhookLanFailed: (reason: string, restored: boolean) => restored
    ? `Couldn't open webhooks to your local network (${reason}), so this is still off: webhooks are accepted from this computer only. Turn it on to try again.`
    : `Couldn't open webhooks to your local network (${reason}), and webhooks from this computer stopped too. Turn it on to try again, or quit and reopen the app.`,
  routineListenerFailing: (provider: string) => `${provider} keeps refusing the saved token — enter it again on this routine and press Connect. Listening resumes as soon as it works.`,
  // Bug 115: the calendar and Mac-folder pollers' siblings of the lines above.
  routineCalendarFailing: (calendarId: string) => `Can't read ${calendarId === "primary" ? "your Google calendar" : `the Google calendar "${calendarId}"`} — use Reconnect Google in Settings if Google asks, and check this Bot still has Google turned on. Watching resumes by itself on the next check that works.`,
  routineMacFolderFailing: (folder: string) => `Can't list the Mac folder "${folder}" — make sure it still exists and is one of your auto-run folders in Settings. Watching resumes by itself on the next listing that works.`,
  routineWontRun: (why: string) => `Turned off — this routine could never run: ${why} Fix it above, then switch it back on.`,
  routinePartlyWontRun: (why: string) => `One of this routine's triggers can't be used: ${why} The others still work.`,
  routineNotWatching: (why: string) => `Not watching yet — ${why}. Add it below and this routine starts watching.`,
  runAborted: "Stopped before it could finish.",
  runAlreadyRunning: "This routine is already running. Wait for it to finish.",
  runGaveUp: (detail: string) => `Gave up after the connection kept dropping: ${detail}`,
  runRetryAbandoned: "The routine could no longer run when the retry was due, so this run was abandoned.",
  runHardLimit: "Stopped after 60 minutes (routine time limit).",
  runRetrying: (attempt: number) => `Retrying after a connection problem (attempt ${attempt} of 3)`,
  runUsageLimit: (hours: number) => `Stopped: Claude usage limit reached (resets in ${hours} h)`,
  routineSoftLimit: "This routine run has been going for 30 minutes. Finish the current step, send the result if your saved instruction calls for one, and end the turn. Put long work in a background task (Task or Shell with block_until_ms: 0).",
  trayRoutineFailed: (name: string) => `Routine "${name}" failed`,
  traySkippedOffline: (n: number) => `${n} routine run${n === 1 ? " was" : "s were"} skipped while ${COMPUTER_NAME} was off`,
  trayRoutinesPausedAway: "Routines on hold while you were away",
  resumeRoutines: "Resume routines",
  keepThemPaused: "Keep them paused",
  spendGuardQuestion: "You've been gone a while — should my routines keep running?",
  spendGuardKeep: "Keep them running",
  spendGuardPauseAll: "Pause them all",
  spendGuardOptOut: "Keep running, don't ask again",
  spendGuardPausedPost: "While you were away I put all your routines on hold so they wouldn't spend for nothing. Should I turn them back on?",
  createdRoutine: "Created Routine",
  routinesCount: (verb: string, n: number) => `${verb} ⏱ ${n} routine${n === 1 ? "" : "s"}`,
  connectSoRoutineCanFire: (platform: string) => `Connect ${platform} so this routine can fire`,
  connect: "Connect",
  publicWebhookUrl: "Public webhook URL",
  addMailbox: "Add mailbox",
  emailPollNote: "Checks email every 15 minutes — each check uses a little of your Claude usage.",
  // bot-to-bot (B2B-*, ORIG-09)
  messaged: "Messaged",
  messagesWith: (n: number) => `${n} message${n === 1 ? "" : "s"} with`,
  nBots: (n: number) => `${n} Bot${n === 1 ? "" : "s"}`,
  noReplyNeeded: "no reply needed",
  messageFrom: "Message from",
  messagesFrom: "Messages from",
  routineOrigin: (name: string) => `Routine · ${name}`,
  followupOrigin: "Follow-up",
  revivalOrigin: (title: string) => `Background task finished · ${title}`,
  cantMessageSelf: "Can't message itself",
  agentGone: "That agent has been deleted",
  unknownAgent: (id: string) => `No Bot or group with id ${id}.`,
  messageAllBots: "Message all Bots…",
  // groups (GRP-*)
  members: "Members",
  addMember: "Add Member",
  groupSettings: "Group settings",
  passedSuffix: "· nothing new to add",
  passedNames: (names: string[]) => `${names.length <= 1 ? names.join("") : `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}`} passed`,
  groupApprovalUnavailable: "This action needs an Auto-review OK, and this conversation can't ask for one. Run it from a one-to-one chat with the assistant.",
  groupsCantDuplicate: "Groups can't be duplicated yet.",
  groupMembersRange: "A group needs 2 to 6 Bots.",
  groupNested: "A group can't contain another group.",
  // control plane (ORIG-17)
  userOnly: (row: string) => `Only the user can change this. Ask them to open Settings → General → ${row}.`,
  cantDeleteSelf: "Not deleted: a Bot can't delete itself.",
  copySuffix: " copy",
  // teach a task (TCH-*)
  teachTask: "Teach a task",
  teachBanner: "Show your Bot a task: say what you want to end up with, then work through it here while it looks on.",
  teachWatching: (subject: string) => `${subject} is watching and taking notes`,
  teachRec: (elapsedMs: number) => `● REC ${Math.floor(elapsedMs / 60_000)}:${String(Math.floor((elapsedMs % 60_000) / 1000)).padStart(2, "0")}`,
  teachPaused: (elapsedMs: number) => `● PAUSED ${Math.floor(elapsedMs / 60_000)}:${String(Math.floor((elapsedMs % 60_000) / 1000)).padStart(2, "0")}`,
  teachContinue: "Continue",
  teachPausedNote: "Paused when the app closed.",
  teachStopSave: "Stop & save",
  teachDiscard: "Discard",
  teachVideoOnly: "Recording video only — your clicks and typing aren't being captured, so the Bot has less to learn from. Stop & save to keep the video, or Discard.",
  teachNoSecrets: "Don't type passwords or other secrets while recording.",
  teachFinishedWake: "Recording done. Work out the task from it.",
  teachRehearsalQuestion: "Test it on a safe example?",
  teachRunRehearsal: "Run a rehearsal",
  teachNotNow: "Not now",
  rehearsalStopped: "Rehearsal: stopped before a real side effect.",
  skills: "Skills",
  privateSkills: "Private skills",
  managePluginsAndSkills: "Manage plugins and skills",
  hiddenBots: "Hidden Bots",
  noHiddenBots: "No hidden Bots",
  showHiddenBots: "Show Hidden Bots",
  unhide: "Unhide",
  hideFromSidebar: "Hide from sidebar",
  markUnread: "Mark as Unread",
  markRead: "Mark as Read",
  editProfile: "Edit Profile",
  duplicate: "Duplicate",
  copyConversationId: "Copy conversation ID",
  shareAsTemplate: "Export Bot…",
  duplicateName: (name: string) => `${name} copy`,
  needsYou: (name: string) => `${name} needs you`,
  waitingForInput: "Waiting for your input.",
  openToSee: `Open ${APP_NAME} to see what it did.`,
  themeRow: (label: string) => `Theme: ${label}`,
  // SET-02: the row is an accelerator for Settings → General → Appearance, so the subtitle names
  // the screen that holds the picker (it used to point at a section that was never built).
  themeSubtitle: "Settings · General · Appearance",
  themeLabels: { system: "Follow system", light: "Light", dark: "Dark" } as Record<string, string>,
  appearance: "Appearance",
  theme: "Theme",
  launchAnimation: "Launch animation",
  launchSound: "Launch sound",
  chatSettings: "Bot",
  /** New-user walk, nit 28: the ⌘K row for this Bot's settings ("Bot" alone was ambiguous). */
  botSettingsRow: "Bot settings",
  currentChat: "Current chat",
  settingsGeneral: "General settings",
  settingsComputer: "Computer settings",
  settingsUsage: "Usage",
  settingsUpdates: "Settings: Updates",
  settingsSubtitle: "Settings",
  // UI polish pass (brief 2): the Settings search field and its miss.
  searchSettings: "Search settings",
  noMatchingSettings: "No matching settings",
  marketplaceSubtitle: "Search plugins and Bots",
  newBot: "New Bot",
  newGroupChat: "New group chat",
  openMarketplace: "Open Marketplace",
  teachATask: "Teach a task",
  skillSaved: "Saved skill",
  attachFiles: "Attach files…",
  photoFromClipboard: "Photo from clipboard",
  useASkill: "Use a skill",
  attachFile: "Attach file",
  reply: "Reply",
  react: "React",
  moreMessageActions: "More message actions",
  copy: "Copy",
  copyText: "Copy text",
  copyCode: "Copy code",
  showAllLines: (n: number) => `Show all ${n} lines`,
  showLess: "Show less",
  showMoreLines: (n: number) => `Show ${n} more line${n === 1 ? "" : "s"}`,
  stepBodyTruncated: "Only part of this was kept.",
  save: "Save",
  open: "Open",
  answered: "Answered",
  skipped: "Skipped",
  dismissed: "Dismissed",
  sendEmail: "Send email",
  discard: "Discard",
  newEmail: "New email",
  readyToSend: "Ready to send",
  submit: "Submit",
  other: "Other…",
  timezoneAuto: (zone: string) => `Auto-detect (${zone})`,
  timezone: "Timezone",
  advanced: "Advanced",
  showAdvanced: "Show advanced controls",
  perTurnRecall: "Per-turn memory recall",
  // cost-diet-2 lever 1 (model routing), off by default.
  saveUsage: "Save usage",
  saveUsageHint: "Use a faster model for simple messages",
  // "Computer perception" (decisions.md 2026-09-21): Screenshots (default) or Live (beta).
  computerPerception: "Computer perception",
  computerPerceptionScreenshots: "Screenshots",
  computerPerceptionLive: "Live (beta)",
  computerPerceptionScreenshotsHint: "Sees the screen as a picture after every action",
  computerPerceptionLiveHint: "Reads the screen as text and gets only what changed. Uses fewer tokens; still being tested",
  compactNow: "Compact now",
  keepMoreHistory: "Keep more history",
  keepMoreHistoryHint: "Every message re-reads the history this Bot keeps before it summarizes. More history remembers more word for word and costs more tokens on every message.",
  newSession: "New session",
  showMemoryFiles: "Show memory files",
  contextMeter: (pct: number, used: string, total: string) => `Context ${pct}% · ${used} of ${total} tokens`,
  tooManyAttachments: "You can attach up to 6 files to a message.",
  fileTooLarge: (name: string, mb: number) => `${name} is larger than ${mb} MB.`,
  importMarkdown: "Paste Markdown…",
  importUrl: "From URL…",
  importFolder: "From folder…",
  importSkill: "Import",
  editSkill: "Edit",
  deleteSkill: "Delete",
  newSkill: "New skill",
  noSkills: "No private skills yet. Ask a Bot to save a process as a skill, or import one.",
  searchNoResults: "No results",
  // Composer: an upload in flight, the clipboard, and a preview that would be a half file (UI fix round: composer)
  sendingAfterUpload: "Sending when the upload finishes\u2026",
  // Bug 198: a message sent while the Bot works waits for its next step, then is shown to it.
  steerQueued: "Queued",
  steerDelivered: "Delivered",
  cancelSend: "Cancel send",
  clipboard: "Clipboard",
  noImageOnClipboard: "No image on the clipboard.",
  tooLargeToPreview: "This file is too large to preview. Use Save to open it outside the app.",
  replyingTo: "Replying to",
  inReplyTo: "reply",
  threadTitle: "Thread",
  // Hand-testing round: "still fetching" must never look like "there is nothing here".
  loading: "Loading…",
};

const startOfDay = (x: Date) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
/** Whole days between the two, by calendar date rather than by elapsed milliseconds. */
const daysApart = (ms: number, nowMs: number) => Math.round((startOfDay(new Date(nowMs)) - startOfDay(new Date(ms))) / 86_400_000);

/**
 * A DAY, and only a day: "Today", "Yesterday", else "Sep 12".
 *
 * This is what the transcript's divider says now. It used to say "Today 9:00 AM" and then, twenty
 * minutes later, "Today 9:20 AM" — a divider that named the same day twice and put a clock time on
 * a rule that is there to separate days. The time was never the divider's job: every turn already
 * carries its own time in its head, so the rule was printing a fact the row beneath it repeats.
 * `timeSeparator` below keeps the day-and-time form, because "Next run Today 7:02 AM" (EventRow) is
 * a sentence about a moment, which is a different thing from a heading over a day's messages.
 */
export function daySeparator(ms: number, nowMs: number): string {
  const days = daysApart(ms, nowMs);
  if (days === 0) return "Today";
  if (days === 1) return "Yesterday";
  return new Date(ms).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

/** CHAT-15: "Today 7:02 AM", "Yesterday 9:43 PM", else "Sep 12 9:43 PM". */
export function timeSeparator(ms: number, nowMs: number): string {
  const time = new Date(ms).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
  return `${daySeparator(ms, nowMs)} ${time}`;
}
