import { ENGINEERING_MODE_EXTRA_TOKENS } from "./bots";
import { FULL_AUTO_SETTINGS_LINE } from "./full-auto";
import { APP_NAME, COMPUTER_NAME, possessive } from "./strings";

const Computer = COMPUTER_NAME.charAt(0).toUpperCase() + COMPUTER_NAME.slice(1);
const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const STR5 = {
  notAvailable: "Not available",
  // Marketplace (Marketplace.dc.html K1–K9; PLG-01, 04, 11, 12; TPL-04)
  marketplace: "Marketplace",
  closeMarketplace: "Close Marketplace",
  yourPlugins: (n: number) => `Your plugins · ${n} installed`,
  yourPluginsAria: (n: number) => `Your plugins, ${n} installed`,
  searchPlaceholder: "Search plugins and Bots",
  clear: "Clear",
  featuredBots: "Featured Bots",
  forYou: "For you",
  becauseYouUse: (name: string) => `Because you use ${name}`,
  fromTeam: `From ${APP_NAME} Team`,
  byTeam: `by ${APP_NAME} Team`,
  authorsBot: (author: string) => possessive(author),
  viewAll: "View all",
  // UI polish pass: connectors show at most five rows a section, then this; one verb per row
  // (Add | Authorize | Manage) with the state as a quiet word beside it.
  showMore: (n: number) => `Show ${n} more`,
  manage: "Manage",
  manageAria: (name: string) => `Manage ${name}`,
  statusConnected: "Connected",
  statusAdded: "Added",
  featuredPlugins: "Featured plugins",
  plugins: "Plugins",
  bots: "Bots",
  add: "Add",
  added: "✓ Added",
  connect: "Connect",
  connected: "✓ Connected",
  authorize: "Authorize",
  waitingForAuthorization: "Waiting for authorization",
  reopen: "Reopen",
  addAria: (name: string) => `Add ${name}`,
  openAria: (name: string) => `Open ${name}`,
  noResults: "No results",
  catalogOffline: "The catalog couldn't be refreshed. Showing the last saved list.",
  // Manage plugins and skills (PLG-02, PLG-08, PLG-09)
  managePlugins: "Manage plugins and skills",
  installedTab: "Installed",
  privateSkillsTab: "Private skills",
  toolsCount: (n: number) => plural(n, "tool", "tools"),
  addCustomServer: "Add custom MCP server",
  serverName: "Name",
  serverUrl: "Server URL",
  serverCommand: "Command",
  // PLG header auth. The common case is one header, so the add form asks for one pair rather than a
  // key/value editor. "Header name" is deliberately literal: the user copies it from the server's
  // own docs (Composio says x-consumer-api-key; other servers say Authorization).
  headerName: "Header name",
  headerValue: "Header value",
  headerHint: "For a server that authenticates with an API key instead of a sign-in. The value is encrypted and never shown again.",
  // Composio is the first header-auth consumer and its docs name this exact
  // pair. The form stays generic; this line appears only when the name or URL already says Composio.
  composioHeaderHint: "Composio uses the consumer key (starts with ck_), not a developer key. The value is encrypted and never shown again.",
  // Slack's hosted MCP rejects dynamic client registration, so Authorize usually
  // dumps the user back into Slack. The working path is a User OAuth Token from api.slack.com/apps.
  slackHeaderHint: "Slack needs a User OAuth Token from api.slack.com/apps (starts with xoxp-), not a bot token. Paste the token — Bearer is added. The value is encrypted and never shown again.",
  githubHeaderHint: "GitHub's hosted MCP doesn't support browser sign-in from here. Paste a personal access token from github.com/settings/tokens (starts with ghp_ or github_pat_). Bearer is added. The value is encrypted and never shown again.",
  oauthNeedsHeader: "This connector doesn't support browser sign-in. Paste an API token under Authentication headers.",
  serverHeaders: "Authentication headers",
  addHeader: "Add header",
  saveHeader: "Save header",
  replaceHeader: (name: string) => `Replace ${name}`,
  removeHeader: (name: string) => `Remove ${name}`,
  accountLabel: "Account label",
  rename: "Rename",
  replace: "Replace",
  remove: "Remove",
  instructions: "Instructions for Bots",
  trustServer: "Trust this server's read-only tools (skip Auto-review for tools it marks read-only)",
  statusLabel: { connected: "Connected", "needs-auth": "Needs sign-in", "waiting-auth": "Waiting for authorization", failed: "Failed", disabled: "Off", unknown: "Not checked yet" } as Record<string, string>,
  turnOn: "Turn on",
  // Bug 54: the server switch is named for what pressing it does, so its name and its state agree.
  turnOff: "Turn off",
  // Bug 37: a list that could not be read says so, instead of reading as empty.
  serversLoadFailed: "Couldn't load your installed plugins.",
  marketplacesLoadFailed: "Couldn't load your plugin marketplaces.",
  skillsLoadFailed: "Couldn't load your private skills.",
  noServers: "No plugins installed yet.",
  noMarketplaces: "No plugin marketplaces added.",
  noSkills: "No private skills yet.",
  marketplaces: "Plugin marketplaces",
  addMarketplace: "Add marketplace",
  marketplaceSource: "GitHub owner/repo or git URL",
  // Connect card (PLG-05) and tool results
  connectCardBody: (name: string, n: number) => `${name} is packaged as a plugin. ${plural(n, "tool", "tools")}`,
  connectorAuthNeeded: (name: string) => `${name} needs to be connected first. The user was shown a connect card for it. Don't try to work around it; wait until they connect it, then try again.`,
  mentionHint: (name: string) => `The user wants you to use ${name} for this`,
  localServerInstall: `Adds a program that runs on ${COMPUTER_NAME}. Review it before allowing.`,
  // Local execution (LOC-04, LOC-06, SET-05, SET-08, LOC-09)
  localCardTitle: "Allow this Bot to run this on your local computer?",
  localCardBody: "“Always allow” covers only this Bot and this kind of action. You can change it in Settings → Computer.",
  localAlways: "Always allow",
  localOnce: "Allow once",
  localNever: "Never",
  localDenyOnce: "Deny once",
  // The outcome lines must match what the answer actually does: "Always" is a per-Bot + per-action grant
  // (asks.ts settle(), coordinator policy.grant), "Never" sets this computer's executionPolicy to Never allow
  // (coordinator daemon.ts). Neither one is "this app and every Bot" (LOC-04).
  localOutcome: {
    always: "Always allowed for this Bot and this kind of action.",
    never: "Running commands on this computer is turned off for every Bot. Change it in Settings → Computer.",
    denied: "This command was not allowed.",
    allowed: "This command was allowed this time.",
    expired: "Withdrawn: this request went unanswered for 7 days, or its Bot was deleted.",
  } as Record<string, string>,
  localNotConnected: `This Mac isn't connected at the moment (the ${APP_NAME} desktop app has to be open and online to run commands here).`,
  localUnavailable: (label: string) => `Your computer "${label}" can't be reached — it seems to be offline.`,
  localNeverPolicy: "Local execution is set to Never allow. Only the user can change this in Settings → Computer.",
  localDeniedTool: "The user did not allow this command on their computer.",
  /** bug 225: the Mac's permission key file (local-policy.key) was changed or can't be read, so nothing can be kept until it is reset. */
  localPolicyKeyBroken: "This Mac's permissions file can't be trusted, so nothing can be saved. Reset permissions in Settings → Computer.",
  resetPermissions: "Reset permissions",
  /** Bug 229: Reset permissions only ever replaces a key file that is broken or tampered with. */
  localPolicyResetRefused: "This Mac's permissions file is fine, so nothing was reset.",
  /** Bug 229: a program that applies a sandbox of its own, run inside the Mac command sandbox. */
  macNestedSandbox: "This program starts a sandbox of its own, which can't run inside this Mac's command sandbox. Swift, Xcode, Playwright, Chromium and Electron run outside it with the user's OK on a card, as one simple command; for anything else, ask the user to run it in their own Terminal.",
  /** Bug 233: a hand-off program (launchctl, cron, at, open, osascript, sfltool) exec'd from inside the command sandbox. */
  macHandoffBlocked: "Programs that start things outside this Mac's command sandbox (launchctl, crontab, at, batch, open, osascript, sfltool) can't be run from inside another command. Run it as a command of its own, so the user can approve it on a card.",
  /** Private-store hardening (fail closed): the command sandbox couldn't be applied, so nothing runs. */
  macSandboxUnavailable: "This Mac's command sandbox couldn't be started, so the command wasn't run. Commands never run without it. Restart Synapse; if it keeps happening, check that /usr/bin/sandbox-exec is present.",
  /** Private-store hardening: a sandboxed command tried to read a private store (the sandbox denies it however it's spelled). */
  macPrivateStoreBlocked: "Saved logins, cookies, Mail, Messages and SSH keys can't be read from inside this Mac's command sandbox. To read one, run a single plain read of that one file as a command of its own (for example `cat <file>`), so the user can approve it on a card.",
  /** Private-store hardening: why a single plain read of a private store needs its own card in every mode. */
  macPrivateStoreRead: "it reads a private store (saved logins, cookies, Mail, Messages or an SSH key) outside this Mac's command sandbox",
  /** mac-keychain-guard: a wrapped command that needed the keychain (which the command sandbox can't reach). */
  macKeychainBlocked: "This needs the macOS keychain, which commands run by Bots can't reach. Ask the user to run it in their own Terminal.",
  /** mac-keychain-guard (ruling): a Mac-side git or gh that needed the user's credentials — Bots never get them. */
  macGithubFromBotComputer: "Bots use GitHub from their own computer (Bot settings → Sign in to GitHub). To push with your own account, run it in your Terminal.",
  /** mac-keychain-guard: Settings → Computer, the Bots' own Claude sign-in. */
  /** Bug 235: the exempt tool's file changed between its card and the run. */
  macToolChanged: "The program changed since its card was shown, so it wasn't run. Run the command again to see the new card.",
  /** Bug 232: exempt programs run one-shot only. */
  macExemptInteractive: "Programs that run outside this Mac's command sandbox run one-shot only: use `swift build`, `swift test` or `swift run`, not the Swift REPL.",
  macExemptNoInput: "That program runs outside this Mac's command sandbox, so nothing can be sent to it. Run it again one-shot with everything it needs on the command line.",
  /** Bug 229: why a known program still needs the card in Full auto. */
  macOutsideSandbox: (what: string) => `${what} runs outside this Mac's command sandbox: it can read anything you can, Synapse's own keys included`,
  /** fix-mac-gate-and-approval-expiry (Bug A): every Mac refusal names the gate that refused and how to change it. */
  macRefused: {
    neverPolicy: "Your Mac's “Run commands on this Mac” is set to Never allow, so no Bot can run anything on it. The user can change it in Settings → Computer.",
    neverRule: (why: string) => `Blocked on this Mac by a fixed safety rule that no mode or setting can lift: ${why}`,
    askNoApproval: "Your Mac's “Run commands on this Mac” is set to Ask every time and no approval arrived for this command. Approve the card, or change this Bot's permission mode (Bot settings → Permission mode, e.g. Full auto) in the app on this Mac.",
    alwaysAsk: (why: string) => `This command always needs the user's OK on this Mac, even in Full auto (${why.replace(/\.$/, "")}). Approve the card to run it.`,
    staleApproval: "This command was not approved on this Mac: the approval sent with it was already used, was for a different command or Bot, or is more than 7 days old. Approve the new card to run it.",
  },
  /** Bug B: the Bot's session ended while a Mac card was waiting. The card stays answerable; the answer wakes the Bot. */
  localAskDetached: "The session ended while this Mac request was waiting for the user. The card stays open: when the user answers it you'll be woken with the decision. Don't retry it now.",
  localAskResumed: (target: string) => `[Mac] The user approved on their Mac: ${target}. Run exactly that again now.`,
  localAskWithdrawn: "This Mac request was withdrawn (unanswered for 7 days, or its Bot was deleted).",
  localAskDeclined: (target: string) => `[Mac] The user did not allow on their Mac: ${target}. Don't retry it; continue without it or ask them.`,
  /** Bug #96 (the same issue as #94): a Mac card ends the turn instead of holding a running slot. */
  localAskWaiting: "Waiting for the user to answer the card on their Mac. End your turn now: when they answer you'll be woken with the decision. Don't retry it now.",
  /** fix-fullauto-adoption: the one Mac-side card that adopts the Bot's mode on this Mac. */
  localAdoptTitle: (bot: string, mode: "accept-edits" | "full-auto") => mode === "full-auto"
    ? `${bot} is set to Full auto. Allow it to run commands on this Mac without asking (except the always-ask and never lists)?`
    : `${bot} is set to Auto-accept edits. Allow it to edit files in your project folders on this Mac without asking (except the always-ask and never lists)?`,
  localAdoptBody: "This is recorded on this Mac only. You can change it any time in Bot settings → Permission mode.",
  localAdoptAllow: "Allow on this Mac",
  localAdoptKeep: "Keep asking",
  localAdoptOutcome: {
    allowed: "Allowed on this Mac.",
    always: "Allowed on this Mac.",
    denied: "This Mac keeps asking for each command.",
    never: "This Mac keeps asking for each command.",
    expired: "Withdrawn: this request went unanswered for 7 days, or its Bot was deleted.",
  } as Record<string, string>,
  localAdoptWaiting: (mode: "accept-edits" | "full-auto") => `This Bot's ${mode === "full-auto" ? "Full auto" : "Auto-accept edits"} isn't set on the user's Mac yet, so the Mac asked them once to allow it. End your turn now: when they answer you'll be woken. Don't retry now.`,
  localAdoptAllowed: (mode: "accept-edits" | "full-auto", targets: string[]) => `[Mac] The user allowed ${mode === "full-auto" ? "Full auto" : "Auto-accept edits"} on their Mac. Run again now what was waiting${targets.length ? `: ${targets.join(" ; ")}` : ""}.`,
  localAdoptKept: (mode: "accept-edits" | "full-auto") => `[Mac] The user chose to keep asking on their Mac instead of ${mode === "full-auto" ? "Full auto" : "Auto-accept edits"}. Each Mac command now shows its own card; re-run only what you still need.`,
  localAdoptRefused: "This Bot's mode isn't set on this Mac yet; the user is asked once to allow it on this Mac.",
  localTooLarge: "Files over 100 MiB can't be copied.",
  computer: "Computer",
  computers: "Computers",
  currentComputer: "Current computer",
  currentComputerHelp: "The Mac you're on right now",
  computerName: "Computer name",
  save: "Save",
  executionOnThisComputer: "Commands on this computer",
  executionOnLocalComputer: "Run commands on this Mac",
  executionHelp: `Let ${APP_NAME} open files and run tasks on your computer. Auto-review still checks everything first.`,
  keepBoxOnQuit: "Keep Bots running when the app quits", // the Bots (the assistants) and their computer, not the app
  keepBoxOnQuitHelp: "When off, the computer stops so this Mac gets RAM and CPU back. Routines pause until you open the app again.",
  policyLabel: { always: "Always allow", ask: "Ask every time", never: "Never allow" } as Record<string, string>,
  // Final secfix round 2 (ruling A): "Always" auto-runs only simple reads inside folders the user adds here.
  autoRunFolders: "Auto-run folders",
  autoRunHelp: "“Always allow” runs simple read-only commands without asking only inside these folders. Everything else still asks.",
  noAutoRunFolders: "No folders yet, so every request asks first.",
  addFolder: "Add folder",
  removeFolder: (p: string) => `Remove ${p}`,
  network: "Network",
  routeTraffic: "Route traffic through this computer",
  routeTrafficOn: "On",
  networkLocked: `${Computer} runs on this Mac, so its traffic already uses this computer's connection.`,
  routed: (n: number) => `${n} routed this session.`,
  notAvailableYet: "Not available yet",
  // Usage & Billing (Usage.dc.html U1–U10; USE-01…06; ORIG-14)
  usageAndBilling: "Usage and billing",
  resetsIn: (days: number) => `Resets in ${plural(days, "day", "days")}`,
  weeklyUsageMenu: (pct: number) => `Weekly usage ${pct}%`,
  // saving-settings: Settings → Usage → Savings (labels only; the one extra line is the measured weekly figure).
  savings: "Savings",
  keepConversationsReady: "Keep conversations ready",
  cacheTtl1h: "1 hour",
  cacheTtl5m: "5 minutes",
  callReplies: "Call replies",
  callRepliesDefault: "Default",
  callRepliesFast: "Fast on the whole call",
  callRepliesMatch: "Match the Bot",
  longContextModel: "Long-context model",
  longContextOn: "On",
  longContextWhenNeeded: "Only when needed",
  weeklyBudget: "Weekly budget (soft)",
  weeklyBudgetHelp: "Pauses routines when reached. Your own messages always go through.",
  budgetNone: "None",
  budgetFixed: "Fixed",
  budgetAmount: "Amount per week (USD)",
  // Hand-testing round: a rejected amount must say so instead of quietly storing "no budget".
  budgetInvalid: "Enter an amount greater than 0, or choose None.",
  thisWeekByBot: "This week by Bot",
  colBot: "Bot",
  colModel: "Model",
  colTurns: "Turns",
  colTokens: "Tokens",
  colCost: "Est. cost",
  thisWeekByKind: "This week by kind of work",
  colKind: "Kind",
  colCalls: "Calls",
  purposeLabels: {
    conversations: "Conversations",
    memory: "Background memory",
    coding: "Coding agents",
    helpers: "Other background helpers",
  } as Record<"conversations" | "memory" | "coding" | "helpers", string>,
  costHistoryNote: (before: string, estimated: number) =>
    `Costs up to ${before} were rebuilt from running totals the app used to store by mistake.` +
    (estimated ? ` ${estimated} ${estimated === 1 ? "entry is an estimate" : "entries are estimates"}.` : ""),
  efficiencyThisWeek: "Efficiency this week",
  tiles: [
    { key: "dropped", title: "Messages dropped", sub: "by the anti-ack gate" },
    { key: "wakesAvoided", title: "Wakes avoided", sub: "info delivered without a turn" },
    { key: "burstsCoalesced", title: "Bursts coalesced", sub: "into one turn each" },
    { key: "loopsEnded", title: "Loops ended", sub: "ping-pong between Bots" },
  ] as const,
  billing: "Billing",
  trayUsage80: "You've used 80% of this week's budget",
  trayBudgetPaused: "Routines on hold: this week's budget is used up",
  resume: "Resume",
  resetsInHours: (h: number) => `It resets in ${plural(h, "hour", "hours")}`,
  limitSkipped: (h: number) => `Skipped: Claude usage limit reached (resets in ${h} h)`,
  limitStopped: (h: number) => `Stopped: Claude usage limit reached (resets in ${h} h).`,
  // Templates (TPL-01…04, S11)
  templateActions: "Template actions",
  shareAsTemplate: "Share as Template",
  viewTemplateDetails: "View template details",
  updateTemplate: "Update template",
  deleteTemplate: "Delete Template",
  reviewTemplate: "Review template",
  templateIncludes: "This template includes",
  factsItKnows: "Facts it already knows",
  playbooks: "Playbooks it can run",
  jobs: "Jobs that run on their own",
  apps: "Apps it can use",
  playbooksShared: "Its playbooks are added to the shared skills folder, so all your Bots can use them.",
  thirdPartyWarning: "This Bot was created by someone else. It may act on your behalf.",
  addBot: "Add Bot",
  needsConnecting: "Needs connecting",
  importBot: "Import Bot…",
  saveTemplate: "Save template",
  copyFilePath: "Copy as file path",
  revealInFinder: "Show in Finder",
  templateSaved: (path: string) => `Saved to ${path}`,
  // Bug 44(b): the preview lists the template's facts by name, so a Bot that starts without them says so.
  templateFactsLost: (name: string) => `${name} started without some of what its template knew`,
  templateFactsLostDetail: (n: number) => `${n} ${n === 1 ? "fact" : "facts"} from the template couldn't be saved to its memory. Tell it in chat what it needs to know.`,
  // Onboarding (ONB-01…06)
  taglineLine1: "Your team of always-on Bots that",
  taglineLine2: "you can give real work to.",
  signIn: "Input API Key →",
  meetApp: `Meet ${APP_NAME}`,
  tourPages: [
    { title: "Bots", body: "Each Bot is a teammate with its own name, instructions and memory. Chats are disposable; Bots are what you keep." },
    { title: `${Computer}`, body: "Your Bots share one computer with a browser, files and apps, so they can do real work while you watch or step away." },
    { title: "Routines", body: "Bots can run jobs on a schedule or when something happens, and tell you what they found." },
  ] as const,
  tourComposer: "Hand off any task to your team of Bots",
  next: "Next",
  back: "Back",
  whatDoYouUse: "What do you use every day?",
  searchTools: "Search tools",
  meetTeammate: "Meet a future teammate",
  createYourOwn: "Create your own",
  getStarted: "Get started",
  suggestions: "Suggestions",
  createFirstBot: "Create your first Bot",
  noChatsYet: "No chats yet",
  toolsAppend: (tools: string[]) => `The user works with ${tools.join(", ")} every day.`,
  setupTitle: `Set up ${COMPUTER_NAME}`,
  startingComputer: "Starting your computer…",
  // Voice (CHAT-08, BOT-24, ORIG-15)
  startVoiceInput: "Start voice input",
  stopVoiceInput: "Stop voice input",
  startVoiceChat: "Start a voice call",
  endVoiceChat: "Hang up",
  listening: "Listening…",
  speaking: "Speaking…",
  // Bug 101: voice mode is a call — it listens, thinks, speaks; mute and end call are real controls.
  voiceThinking: "Thinking…",
  voiceMuted: "Muted",
  voiceMute: "Mute microphone",
  voiceUnmute: "Unmute microphone",
  // Voice calls (the call screen).
  callTimer: (ms: number) => { const s = Math.max(0, Math.floor(ms / 1000)); return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`; },
  callYou: "You",
  callMicLevel: "Your microphone",
  callCaptions: "Captions",
  callApprovalLine: (what: string) => `I need your OK to ${what.replace(/[.\s]+$/, "").replace(/^./, (c) => c.toLowerCase())}.`,
  callAddBot: "Add a Bot to the call",
  /** Phase 2 (bug 213): the palette's "call nova scout" row. */
  paletteCallBots: (names: string[]) => `Call ${names.length > 1 ? `${names.slice(0, -1).join(", ")} and ${names.at(-1)}` : names[0] ?? ""}`,
  callRemoveBot: (name: string) => `Remove ${name} from the call`,
  callParticipants: "In this call",
  // Bug 158: taking ONE Bot off the call — the × on its avatar and the right-click / long-press menu.
  callBotActions: (name: string) => `${name} on this call`,
  callRemoveFromCall: "Remove from call",
  callCantRemoveAnchor: (name: string) => `${name} started this call and stays on it — hang up to end the call`,
  // Adding Bots to any call (bug 108): up to 6 Bots, a type-to-filter dropdown, a note in each joiner's chat.
  callFull: "Up to 6 Bots on a call",
  callAddFilter: "Find a Bot",
  callNoOtherBots: "No other Bots to add",
  callJoinedNote: (chat: string, len: string) => `Joined a call in ${chat} · ${len}`,
  callStartedWith: (names: string) => `Voice call started · ${names}`,
  callEndedWith: (len: string, names: string) => `Voice call ended · ${len} · ${names}`,
  callJoined: (name: string) => `${name} joined the call`,
  callLeft: (name: string) => `${name} left the call`,
  callOpenChat: "Open",
  interrupted: "(interrupted)",
  // Dictation ended because nobody spoke: said plainly, never a silent stop.
  dictationNoSpeech: "Didn't hear anything. Press the mic and speak.",
  voice: "Voice",
  speed: "Speed",
  language: "Language",
  notSet: "Not set",
  autoDetect: "Auto-detect",
  usedBy: (bot: string) => `Used by ${bot}`,
  micDenied: "Microphone or speech recognition access is off. Turn it on in System Settings → Privacy & Security.",
  // Bug 96: each permission fault names the one switch that fixes it; the UI adds a button to that pane.
  micAccessDenied: "Synapse can't use the microphone. Turn on Synapse in System Settings → Privacy & Security → Microphone.",
  micAccessRestricted: "Microphone access is blocked on this Mac (by a profile or Screen Time), so Synapse can't turn it on.",
  speechAccessDenied: "Synapse can't turn speech into text. Turn on Synapse in System Settings → Privacy & Security → Speech Recognition.",
  speechAccessRestricted: "Speech recognition is blocked on this Mac (by a profile or Screen Time), so Synapse can't turn it on.",
  openPrivacySettings: "Open System Settings",
  voiceRestartFailed: "Voice chat stopped because the microphone kept dropping out. Check microphone access and try again.",
  // The send failed outright: the Bot never heard it, so the user has to say it again.
  voiceSendFailed: "That message didn't get through. Listening again — try saying it once more.",
  // The send went out but nothing speakable came back within the timeout (a card, a widget, an
  // attachment — or a very slow turn). Voice mode carries on listening.
  voiceNoSpokenReply: "That reply didn't come back as speech. Listening again.",
  // Bug 104: choosing the microphone and speaker (Settings → Voice, and the voice-call switcher).
  voiceSettingsHelp: "The microphone and speaker used for dictation and voice chat.",
  microphone: "Microphone",
  speaker: "Speaker",
  audioDevices: "Audio devices",
  systemDefault: (name: string | null) => (name ? `System default (${name})` : "System default"),
  savedDeviceNotConnected: "Saved device (not connected)",
  transportLabel: { "built-in": "Built-in", usb: "USB", bluetooth: "Bluetooth", "bluetooth-le": "Bluetooth", hdmi: "HDMI", displayport: "DisplayPort", airplay: "AirPlay", thunderbolt: "Thunderbolt", pci: "PCI", firewire: "FireWire", virtual: "Virtual", aggregate: "Aggregate", continuity: "iPhone" } as Record<string, string>,
  inputLevel: "Input level",
  inputLevelHelp: "Speak — the bar moves when the microphone hears you.",
  testSpeaker: "Test speaker",
  // Bug 106: the voice calls speak with.
  callVoice: "Voice",
  callVoiceHelp: "How Bots sound in a voice call. A Bot with its own voice (Bot settings) keeps it.",
  voiceAutomatic: (name: string | null) => (name ? `Automatic (${name})` : "Automatic"),
  voiceQuality: { premium: "Premium", enhanced: "Enhanced", default: "Basic" } as Record<"premium" | "enhanced" | "default", string>,
  // Bug 157: a Bot's saved voice that this Mac no longer has (a deleted download, or a Kokoro
  // choice while Kokoro isn't running) — said plainly instead of the row reading "Not set".
  savedVoiceNotInstalled: "Saved voice (not installed)",
  previewVoice: "Preview",
  previewingVoice: "Playing…",
  onlyBasicVoices: "Only basic voices are installed, so calls sound robotic. Download an Enhanced or Premium voice (System voice → Manage Voices…).",
  betterVoicesHint: "More natural voices can be downloaded in System Settings.",
  downloadVoices: "Download voices…",
  voicesUnavailable: "Couldn't list the voices.",
  testingSpeaker: "Playing…",
  speakerTestFailed: (why: string) => `Couldn't play the test sound: ${why}`,
  devicesUnavailable: "Couldn't list the audio devices.",
  meterUnavailable: (why: string) => `The microphone didn't start: ${why}`,
  echoUnavailable: "Echo cancellation isn't available with this device combination.",
  // Bug 213: a Bluetooth headset's own mic would drop it to mono; the call uses the Mac's mic instead.
  micKeepsStereo: "Using the Mac's mic so your headset stays in stereo.",
  deviceFellBack: (kind: "input" | "output", name: string, fallback: string) =>
    `${name || (kind === "input" ? "The microphone" : "The speaker")} disconnected — using ${fallback || "the system default"} for now.`,
  deviceRestored: (name: string) => `${name || "Your device"} is back and selected again.`,
  // Bug 107: Kokoro, the local neural ("Natural") voice engine.
  naturalVoices: "Natural (Kokoro)",
  appleVoices: "Apple voices",
  naturalStatusLabel: "Natural voices (Kokoro)",
  naturalStatus: { ready: "Ready", missing: "Not found", checking: "Checking…" } as Record<"ready" | "missing" | "checking", string>,
  naturalStatusHelp: "Free, offline neural voices that run on this Mac. Apple voices are the fallback.",
  naturalVoiceLabel: (name: string, accent: string) => `${name} · ${accent}`,
  naturalAutomatic: "Automatic (a natural voice for each Bot)",
  naturalVoiceFellBack: "The natural voice didn't play, so this line used the Apple voice.",
  // Bug 157: what each engine costs, said plainly — one line each, next to the picker that offers both.
  naturalEngineNote: "Natural (Kokoro) voices run on this Mac and use about 800 MB while loaded.",
  appleEngineNote: "Apple voices are built into macOS and start instantly.",
  // UI polish pass (brief 2): the engine notes become a labelled group of facts, not a wall of text.
  voiceMemory: "Memory while loaded",
  memoryNatural: "800 MB",
  memoryQwen: "2.1 GB",
  memoryCloned: "1.4 GB",
  memoryApple: "Built in",
  // Cloned voices (F5). The numbers are measured on an M1 Pro, not estimates: about 1.7 GB of
  // weights plus a 0.3 GB Python environment on disk, ~1.4 GB resident while loaded, and a whole
  // sentence rendered before a word of it plays (roughly 7 s for a short line).
  clonedVoices: "Cloned voice (F5)",
  clonedEngineNote: "A cloned voice speaks in a voice you recorded. It needs about 2 GB on disk and 1.4 GB of memory while it speaks, and it renders a whole sentence before playing it — so calls open in this Bot's natural voice and switch over.",
  clonedVoiceLabel: (name: string) => name,
  clonedStatusLabel: "Cloned voices (F5)",
  clonedStatus: { ready: "Ready", "no-voices": "No voices recorded", missing: "Not installed", checking: "Checking…" } as Record<string, string>,
  // ---- Qwen3, bug 164 ----
  qwenVoices: "Qwen3 (natural)",
  qwenStatusLabel: "Qwen3 voices",
  qwenStatus: { ready: "Ready", missing: "Not installed", checking: "Checking…" } as Record<string, string>,
  qwenVoiceLabel: (name: string, accent: string) => `${name} · ${accent}`,
  qwenEngineNote: "Qwen3 voices run on this Mac and use about 2.1 GB while loaded. The first sentence of each reply speaks in this Bot's Kokoro voice so the call opens straight away, and the rest streams from Qwen3.",
  qwenNotInstalled: "Qwen3 isn't set up yet. Run app/native/qwen/install.sh to build its Python environment.",
  // ---- voice mode, bug 164: one control, two measured numbers ----
  voiceModeLabel: "Voice quality",
  voiceModeLight: "Light",
  voiceModeFull: "Full",
  /** One factual line per mode: what it holds in memory, and how long until the first word. */
  voiceModeFact: (memoryMb: number, firstWordMs: number) =>
    `${memoryMb >= 1000 ? `${(memoryMb / 1000).toFixed(1)} GB` : `${memoryMb} MB`} while a call runs · first word in ${(firstWordMs / 1000).toFixed(2)} s`,
  /** One option of the control, on one line: its name, what it holds, and what it does. */
  voiceModeOption: (name: string, fact: string, what: string) => `${name} — ${fact} · ${what}`,
  voiceModeLightWhat: "Kokoro speaks, Apple's recognizer listens.",
  voiceModeFullWhat: "Qwen3 speaks, Whisper re-checks what it heard, cloned voices available.",
  voiceModeTakesEffect: "A change applies to your next call; a call in progress is left alone.",
  /** A Bot set to a voice this mode can't load. Said in that Bot's settings, not as a warning. */
  voiceModeBlocked: (engine: string) => `${engine} needs Full voice quality. This Bot speaks in its Kokoro voice until you switch.`,
  /** The call screen, once, when the Mac ran low on memory mid-call. */
  voiceModeDroppedLowMemory: "This Mac ran low on memory, so the rest of this call uses the lighter voice.",
  // ---- the recorder ----
  recordVoice: "Record a voice",
  recordVoiceHelp: "Read one sentence out loud. Seven to ten seconds is enough to clone from.",
  recordStart: "Record",
  recordStop: "Stop",
  recordRetake: "Retake",
  recordSave: "Save voice",
  recordSaving: "Saving…",
  recordElapsed: (s: number) => `${Number(s).toFixed(1)}s`,
  recordTarget: "7–10s",
  recordTooShortYet: "Keep going…",
  recordInWindow: "Good — stop when you finish the sentence.",
  recordTooLong: "That's long enough — stop now.",
  recordScript: "What to read",
  recordOwnWords: "Use my own words",
  recordTranscript: "What the clip says",
  recordTranscriptHelp: "This must match the recording word for word, including punctuation.",
  recordSaidDifferently: "I said it differently",
  recordChecks: "Checks",
  recordNameLabel: "Name",
  recordNamePlaceholder: "My voice",
  recordPreview: "Preview",
  recordPlayReference: "Play my recording",
  recordNoMic: "No microphone is available for recording.",
  recordFailed: (why: string) => `That recording couldn't be used: ${why}`,
  clonedVoiceSaved: (name: string) => `Saved “${name}”. Choose it as a Bot's voice above.`,
  clonedVoiceDelete: (name: string) => `Delete “${name}”? This removes the recording from this Mac.`,
  clonedVoiceUsedBy: (names: string) => `Used by ${names}`,
  clonedVoiceRename: "Rename",
  clonedVoiceReRecord: "Re-record",
  clonedVoiceDeleteAction: "Delete",
  // Coding agent (TOOL-20)
  codingAgent: "Coding agent",
  codingStatus: { running: "Working", done: "Done", error: "Failed", cancelled: "Cancelled", "timed-out": "Timed out" } as Record<string, string>,
  openPr: "Open pull request",
  steerTimeUp: "[Update from the agent that started you] You're almost out of time. Don't begin anything new; wrap up with a report of what's finished and what remains.",
  // Avatars (BOT-18, N10, N13, N14)
  avatarTabBot: "Bot",
  avatarTabGenerate: "Generate",
  avatarTabUpload: "Upload",
  describeAvatar: "Describe your avatar",
  generate: "Generate",
  generating: "Generating…",
  dropImage: "Drag, drop, or paste an image",
  or: "or",
  browseFiles: "Browse files",
  avatarTooLarge: "Images can be at most 5 MB.",
  avatarBadType: "Use a PNG, JPG, WebP, GIF or SVG image.",
  // Memory, follow-ups (MEM-07, ORIG-11)
  memory: "Memory",
  memoryStandard: "Standard",
  memoryDreaming: "Dreaming",
  proactiveFollowups: "Proactive follow-ups",
  // Copy link to this setting (SET-18)
  copyLink: "Copy link to this setting",
  linkCopied: "Link copied",
  // System (Task 6: Settings six sections)
  system: "System",
  // Updates (SET-12, UI-03)
  updates: "Updates",
  app: "App",
  updateSource: "Repository",
  updateToken: "Read-only token",
  updateSourceSaved: "Saved",
  automaticUpdates: "Automatic Updates",
  version: (v: string) => `Version ${v}`,
  updateReady: (v: string) => `${APP_NAME} ${v} is ready. Restart to apply.`,
  restartToUpdate: "Restart to Update",
  updateAvailable: (v: string) => `${APP_NAME} ${v} is available.`,
  downloadUpdate: "Download Update",
  checkForUpdates: "Check for Updates",
  checking: "Checking…",
  upToDate: "You're up to date",
  // Hand-testing round: every status the updater can emit needs a line on screen.
  noUpdateSource: "No update source is set, so there's nothing to check for.",
  downloading: "Downloading…",
  newUpdate: "New update available",
  install: "Install",
  // Palette (PAL-04, P5, P6)
  paletteMarketplaceSub: "Search plugins and Bots",
  paletteResultSub: "Marketplace",
  engineeringMode: "Engineering mode",
  // D13-B: UI copy never names the vendor harness (shared/test/phase5.test.ts), so "the full engineering prompt".
  engineeringModeHint: `Uses the full engineering prompt — better for coding, costs about ${ENGINEERING_MODE_EXTRA_TOKENS.toLocaleString("en-US")} more tokens per message.`,
  /** UI polish pass: the real number, a quiet value beside the switch instead of a sentence under it. */
  engineeringModeCost: `+${ENGINEERING_MODE_EXTRA_TOKENS.toLocaleString("en-US")} tokens`,
  engineeringChip: "Engineering",
  // feat-mac-access-parity: the per-Bot permission mode (Claude Code parity). Neutral copy; the warning is on Full auto.
  permMode: "Permission mode",
  permModeHint: "How this Bot handles edits and commands on your computer and the box.",
  permModeAsk: "Ask",
  permModeAskHelp: "Edits and commands ask you the first time. Always-allow rules still apply. Recommended.",
  permModeAcceptEdits: "Auto-accept edits",
  permModeAcceptEditsHelp: "File edits inside your project folders run without asking. Commands still ask.",
  permModeFullAuto: "Full auto",
  // full-auto-quiet: one short factual line naming what still asks. No marketing copy.
  permModeFullAutoHelp: FULL_AUTO_SETTINGS_LINE,
  /** Bug 256: the one prompt after a permission reset (or a Bot whose chosen mode isn't on this Mac). */
  macModesResetTitle: (reset: boolean, names: string[], fullAuto: boolean) => reset
    ? `Your Mac permissions were reset. Turn ${fullAuto ? "Full auto" : "Bot modes"} back on for: ${[names].flat().join(", ")}`
    : `Turn on ${fullAuto ? "Full auto" : "Bot modes"} on this Mac for: ${[names].flat().join(", ")}`,
  macModesRestore: (reset: boolean, fullAuto: boolean) => `Turn ${fullAuto ? "Full auto" : "Bot modes"} ${reset ? "back on" : "on"}`,
  macModesNotNow: "Not now",
  /** fix-fullauto-adoption: shown in Bot settings when this Mac's own record of the mode differs from the Bot's. */
  permModeNotOnMac: "Not yet allowed on this Mac, so it still asks for each command here.",
  permModeApplyOnMac: "Allow on this Mac",
  permModeFullAutoWarning: `In Full auto this Bot edits files and runs commands without asking. ${FULL_AUTO_SETTINGS_LINE}`,
  permModeFullAutoChip: "Full auto",
  // Bug 258: No limits. A label only; the one confirm carries the risk sentence.
  permModeNoLimits: "No limits",
  noLimitsConfirmTitle: "Turn on No limits?",
  noLimitsConfirmLine: "No limits removes the remaining asks for private files, sending and your SSH and GitHub access on this Mac. A Bot tricked by content it reads could access private files or send data out without asking.",
  noLimitsConfirmVerb: "Turn on No limits",
  noLimitsNeedsConfirm: "No limits can only be turned on from the confirm in Bot settings.",
  engineeringOfferTitle: "Switch this Bot to Engineering mode?",
  engineeringOfferBody: "That switches it to the full engineering prompt, better for code, git and tests. You can turn it off in its settings.",
  turnOnEngineering: "Turn on",
  notNow: "Not now",
};
