/** Wave 4.1: Settings → System → Telegram, and what the bridge says in Telegram. Titles and labels only. */
export const STR_TELEGRAM = {
  title: "Telegram",
  access: "Telegram",
  token: "Bot token",
  tokenPlaceholder: "123456:ABC…",
  save: "Save",
  bot: "Bot",
  remove: "Remove",
  pair: "Pair",
  pairingCode: "Pairing code",
  openTelegram: "Open in Telegram",
  cancel: "Cancel",
  pairedWith: "Paired with",
  unpair: "Unpair",
  working: "Working…",
  errors: {
    "bad-token": "That token didn't work",
    "token-rejected": "Telegram rejected the token",
    conflict: "Another program is using this bot",
    network: "Can't reach Telegram",
    "no-secrets": "Synapse's secrets aren't open yet",
    "no-token": "Add a bot token first",
  } as Record<string, string>,
  // In Telegram (plain text, never parsed as markup).
  chat: {
    paired: "Paired with Synapse.",
    help: "Send a message to talk to your Bot.\n/bots lists your Bots\n/bot <name> picks one\n/stop stops it",
    chosen: (name: string) => `Talking to ${name}.`,
    choose: "Pick a Bot: /bot <name>",
    noBots: "No Bots yet.",
    notFound: (name: string) => `No Bot called ${name}.`,
    bots: (names: string[], current: string | null) => names.map((n) => (n === current ? `${n} (current)` : n)).join("\n"),
    stopped: (name: string) => `Stopped ${name}.`,
    forwarded: "Forwarded messages aren't sent to Bots.",
    textOnly: "Only text for now.",
    slowDown: "Slow down a little.",
    notConnected: "Synapse isn't connected yet.",
    couldntSend: "Couldn't send that.",
    approve: "Approve",
    deny: "Deny",
    expired: "Expired",
    outcome: { approved: "Approved", always: "Approved", allowed: "Approved", denied: "Denied", never: "Denied", expired: "Expired", stopped: "Stopped", pending: "Waiting" } as Record<string, string>,
    truncated: (n: number) => `…${n.toLocaleString("en-US")} more characters`,
    partHidden: "Part of this is hidden here.",
    openInSynapse: "Open in Synapse to read all of it.",
    moreInApp: "…the rest is in Synapse.",
  },
} as const;
