/** Bug 198: Settings → Voice → Phone access. Titles and labels only (no explanatory second lines). */
export const STR_PHONE = {
  title: "Phone access",
  address: "Address",
  copy: "Copy",
  copied: "Copied",
  qrLabel: "QR code for the Phone access address",
  pairPhone: "Pair a phone",
  pairingCode: "Pairing code",
  cancel: "Cancel",
  devices: "Paired phones",
  revoke: "Revoke",
  revokeDevice: (name: string) => `Revoke ${name}`,
  lastSeen: (when: string) => `Last used ${when}`,
  inCall: "On a call",
  enableServe: "Turn on HTTPS in Tailscale",
  openTailscale: "Open",
  tailscaleMissing: "Tailscale isn't installed",
  tailscaleStopped: "Tailscale isn't connected",
  noMagicDns: "MagicDNS is off in Tailscale",
  getTailscale: "Get Tailscale",
  working: "Working…",
  retry: "Retry",
  unreachable: "Tailscale couldn't reach Synapse's private socket",
  noUnix: "This Tailscale can't serve a private socket — update Tailscale",
  tooOld: "Update Tailscale to 1.56 or newer",
  portInUse: "HTTPS port 443 is already used by your own Tailscale Serve setup",
  funnelOn: "Funnel is on for port 443 in Tailscale — turn it off first",
  serveStatus: "Couldn't read Tailscale Serve's settings",
  notMapped: "Tailscale Serve didn't point at Synapse",
  notOurs: "Something other than Synapse answered on the Tailscale address",
  unsafeDir: "Synapse's socket folder isn't private",
  socket: "Synapse couldn't open its private socket",
  offFailed: "Couldn't remove the Tailscale mapping yet — retrying",
  shared443: "Remove Synapse's phone mapping in Tailscale, or your other :443 handlers, then retry",
  failed: (why: string) => `Couldn't turn on: ${why}`,
} as const;
