/** Safety v2: Settings → Rules, the Bot's own rules and network, and the card's rule line. Short labels, no subtitles. */
export const STR_RULES = {
  rules: "Rules",
  preset: "Preset",
  presetCustom: "Custom",
  presetStops: "Stops asking",
  presetStarts: "Asks",
  presetStricter: "Stricter",
  presetSwitch: (name: string) => `Switch to ${name}`,
  presetNoChange: "No change",
  addRule: "Add rule",
  rulePlaceholder: "e.g. Never email eve@example.com",
  botRulePlaceholder: "e.g. Ask before deletes",
  ruleCol: "Rule",
  typeCol: "Type",
  presetTag: "Preset",
  reviewTag: "Checked by Auto-review",
  preview: (changed: number, of: number) => (of === 0 ? "No recent actions to compare" : `Would have changed ${changed} of your last ${of} actions`),
  asException: (rule: string) => `Add as exception to ${rule}`,
  ruleOn: (text: string) => `Rule on: ${text}`,
  deleteRule: (text: string) => `Delete rule: ${text}`,
  ruleType: (text: string) => `Type of rule: ${text}`,
  removeExcept: (what: string) => `Remove exception: ${what}`,
  guidelines: "Guidelines",
  guidelinePlaceholder: "e.g. Draft, don't send.",
  addGuideline: "Add",
  deleteGuideline: (text: string) => `Delete guideline: ${text}`,
  network: "Network",
  networkOpen: "Open",
  networkOnly: "Only these sites",
  networkBlock: "Block these sites",
  networkHosts: "Sites",
  networkPlaceholder: "github.com, pypi.org",
  save: "Save",
  thisBotsRules: "This Bot's rules",
  cardRule: "Rule",
  /** The Mac's own gate, applying the owner's rules. */
  macNever: (rule: string) => `Your rule “${rule}” blocks this on your Mac.`,
  macAsk: (rule: string) => `Your rule “${rule}” asks first.`,
  makeRule: "Make this a rule…",
  loosenRule: "Loosen this rule…",
} as const;
